title: Dereel
tagline: Dereel's Community Website

profiles:
  development:
    short_name: Dev
  production:
    short_name: Home
    base_url: http://dereel.com.au
    google_analytics: UA-17125325-2
    minify: true
    deploy:
      host: wp01.westonwire.com.au
      path: /var/www/dereel.com.au/html/
