title: Dereel
tagline: Dereel's Community Website
author: Dereel Community Project
profiles:
  development:
    short_name: Dev
    disqus: dereel
    disqus_developer: true
  production:
    short_name: Home
    base_url: http://dereel.com.au
    google_analytics: UA-17125325-2
    disqus: dereel
    minify: true
    deploy:
      host: bird.westonwire.com.au
      path: /srv/dereel.com.au/html/
      uncommitted: true
